run:
  timeout: 5m
  go: "1.22"
  skip-dirs:
    - vendor
    - examples/basic/terraform/.terraform

output:
  format: colored-line-number

linters-settings:
  goimports:
    local-prefixes: github.com/marcy326/tfve
  
  lll:
    line-length: 120

linters:
  enable:
    # Essential linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    
    # Code quality
    - goimports
    - goconst
    - misspell
    - unconvert
    - lll

issues:
  exclude-use-default: true
  
  exclude-rules:
    # Allow longer lines in tests
    - path: _test\.go
      linters:
        - lll